name: Publish

on: workflow_dispatch

env:
  mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
  mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
  inMemorySigningKey: ${{ secrets.GPG_K }}
  inMemorySigningKeyPassword: ${{ secrets.GPG_P }}

jobs:
  publish-others:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: corretto
      - name: Grant Gradle Wrapper Permission
        run: chmod +x gradlew
      - name: Publish
        run: ./gradlew publish --stacktrace        
  publish-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: corretto
      - name: Grant Gradle Wrapper Permission
        run: chmod +x gradlew
      - name: Publish
        run: ./gradlew publishMingwX64PublicationToMavenRepository --stacktrace
