name: Publish

on: workflow_dispatch

env:
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  GPG_K: ${{ secrets.GPG_K }}
  GPG_P: ${{ secrets.GPG_P }}

jobs:
  publish-others:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: corretto
      - name: Grant Gradle Wrapper Permission
        run: chmod +x gradlew
      - name: Publish
        run: ./gradlew publish --stacktrace        
  publish-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: corretto
      - name: Grant Gradle Wrapper Permission
        run: chmod +x gradlew
      - name: Publish
        run: ./gradlew publishMingwX64PublicationToMavenRepository --stacktrace
